name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QuanEstimation_COMPILE: "n"
      PYTHON_JULIACALL_COMPILE: "no"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - uses: julia-actions/setup-julia@v2
      with:
        version: '1.11'  
    - run: julia -e 'using Pkg;Pkg.add(name="QuanEstimation",version="0.1.6");Pkg.add("PyCall");using QuanEstimation'

    - name: Install dependencies
      run: |
        pip install .[test]
        pip install pytest-cov 

    - name: Run tests 
      run: |
        export PYTHON_JULIACALL_COMPILE="no"
        export QuanEstimation_COMPILE="n"
        coverage run --source=quanestimation -m pytest -s --junitxml=test-results.xml 
        coverage xml

    - name: Upload report to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: QuanEstimation/QuanEstimation
        files: coverage.xml
        verbose: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: QuanEstimation/QuanEstimation
        files: ./test-results.xml
