name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QuanEstimation_COMPILE: "n"
      PYTHON_JULIACALL_COMPILE: "no"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Cache Julia packages
      uses: actions/cache@v4
      env:
        cache-name: cache-julia-packages
      with:
        path: ~/.julia
        key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-

    - uses: julia-actions/setup-julia@v2
      with:
        version: '1.11'  # Use specific version for stability

    - name: Install Julia dependencies
      run: |
        julia -e 'using Pkg;
                  Pkg.add(name="QuanEstimation", version="0.1.6");
                  Pkg.add("PyCall");
                  Pkg.precompile()'

    - name: Install dependencies
      run: |
        pip install .[test]
        pip install pytest-cov 

    - name: Run tests 
      run: |
        export PYTHON_JULIACALL_COMPILE="no"
        export QuanEstimation_COMPILE="n"
        coverage run --source=quanestimation -m pytest -s --junitxml=test-results.xml 
        coverage xml

    - name: Upload report to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: QuanEstimation/QuanEstimation
        files: coverage.xml
        verbose: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: QuanEstimation/QuanEstimation
        files: ./test-results.xml
