name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JULIA_PROJECT_COMPILE: no

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install .[test]

    - name: Check env
      run: env    

    - name: Run tests with coverage
      run: |
        export JULIA_PROJECT_COMPILE=no
        coverage run --source=quanestimation -m pytest -s

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.QUANESTIMATION_TOKEN }}
        slug: LiuJPhys/QuanEstimation