name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_JULIACALL_COMPILE: no
      PYTHON_JULIACALL_COMPILED_MODULES: no

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - uses: julia-actions/setup-julia@v2
      with:
        version: '1.10'
    - run: julia -v

    - name: Install dependencies
      run: |
        pip install .[test]
        pip install pytest-cov

    - name: Check env
      run: env    

    - name: Run tests 
      run: |
        export PYTHON_JULIACALL_COMPILE=no
        export PYTHON_JULIACALL_COMPILED_MODULES=no
        coverage run --source=quanestimation -m pytest -s
        # pytest --cov --cov-branch --cov-report=xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.QUANESTIMATION_TOKEN }}
        slug: LiuJPhys/QuanEstimation